# Generated by Django 6.0.4 on 2026-04-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('technician', 'Technician'), ('admin', 'Admin'), ('farmer', 'Farmer')], default='worker', max_length=20),
        ),
    ]
