# Generated by Django 6.0.4 on 2026-04-18 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('ppe', 'Industrial Safety (PPE)'), ('marine', 'Marine Contamination'), ('land', 'Land Regeneration')], max_length=20)),
                ('source', models.CharField(choices=[('upload', 'File Upload'), ('camera', 'Live Camera')], default='upload', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logs/photos/%Y/%m/')),
                ('video', models.FileField(blank=True, null=True, upload_to='logs/videos/%Y/%m/')),
                ('result_data', models.JSONField(default=dict)),
                ('zone_name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('non_resolved', 'Non Resolved')], default='in_progress', max_length=20)),
                ('label_note', models.TextField(blank=True)),
                ('labeled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_logs', to=settings.AUTH_USER_MODEL)),
                ('labeled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labeled_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Log',
                'verbose_name_plural': 'Incident Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
